# -*- coding: utf-8 -*-
"""Ordenar_cadena.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17PuoPjwHSDndplEL96lTucWLCjN5w9Lc

# Reto 4: Ordenar cadena de caracteres
Escriba una función que reciba una cadena de caracteres (str) por parámetro y retorne dicha cadena ordenada alfabéticamente.

Por ejemplo, si se recibe la palabra "bca", el retorno correcto sería "abc".

Suponga que las palabras que su función deberá ordenar están compuestas únicamente del alfabeto inglés en minúsculas. La cadena no tiene espacios.

Su solución debe tener una función de acuerdo con la siguiente especificación:

**Nombre de la función: ordenar_cadena**

Si lo requiere, puede agregar funciones adicionales.
"""

def ordenar_cadena(cadena:str)->str:
    ordenado = sorted(cadena)
    salida = "".join(ordenado)
    return salida