# -*- coding: utf-8 -*-
"""Reto 2: Mismos dígitos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N8t7tpJq-TZh1oOlyqJAwchdObbGTeD5

# Reto 2: Mismos dígitos
Escriba una función que determine si en dos números enteros aparecen los mismos dígitos. No tenga en cuenta ni la frecuencia ni el orden de aparición de los dígitos en los números.

Los números no tienen necesariamente la misma cantidad de dígitos. Por ejemplo, si los números son 998 y 89 la función debería retornar True.

   

Su solución debe tener una función de acuerdo con la siguiente especificación:

**Nombre de la función: mismos_digitos**

Si lo requiere, puede agregar funciones adicionales.
"""

def mismos_digitos (a:int, b:int)-> bool:
   
    
    cadena_a = [int(i) for i in str(a)]
    cadena_b= [int(i) for i in str(b)]
    resultado = False
    
    for i in cadena_a:
        resultado = False
        for j in cadena_b:
            if i == j:
                resultado = True
                break
        if resultado == False:
            return resultado
        
    for i in cadena_b:
        resultado = False
        for j in cadena_a:
            if i == j:
                resultado = True
                break
        if resultado == False:
            return resultado
    return resultado