# -*- coding: utf-8 -*-
"""Manipulacion Diccionarios.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vNp1tpw92EafIrg6YNMXznmWO_8UZI5v

# Reto 8: Ash y la liga Kalos
Ash Ketchum, el personaje principal del anime Pokémon, está a punto de luchar en la final de la liga Kalos. En estos eventos compiten los mejores entrenadores del mundo en batallas donde cada entrenador puede tener 3, 4, 5 o 6 criaturas. Ash quiere saber, para una cantidad de criaturas específica, si él podrá formar un equipo únicamente con Pokémon seudolegendarios para competir en la final. Un pokemon seudolegendario es aquel que en la suma de sus estadísticas de combate tiene 600 puntos o más.

Las estadísticas de combate de cada pokemon son 6:  


*   "ataque"
*   "defensa"

*   "ataque_especial"
*   "defensa_especial"

*   "velocidad"
*   "vida" 

Escriba una función que, dada una lista de diccionarios (cada uno representando un pokémon) con las anteriores estadísticas, determine si Ash podrá formar un equipo de pokémon seudolegendarios para afrontar la final de la liga. En caso que Ash pueda formar un equipo, retorne una lista con los nombres de las criaturas que Ash utilizaría en la batalla. Si es imposible generar un equipo que cumpla con las condiciones, retorne None.

Se garantiza que en caso de poder formar un equipo válido, solamente habrá una configuración posible.  

La lista de retorno debe componerse únicamente de cadenas de caracteres y debe tener el mismo orden de la lista que llega por parámetro.  

Su solución debe tener una función de acuerdo con la siguiente especificación: 

**Nombre de la función: construir_equipo_pokemon**

Si lo requiere, puede agregar funciones adicionales.
"""

def construir_equipo_pokemon(Cantidad:int,lista_pkmn:list)->list:
    pseudo = []
    total_i = 0
    for i in range (0,len(lista_pkmn)):
        total_i = lista_pkmn[i]["vida"]+lista_pkmn[i]["ataque"]+lista_pkmn[i]["defensa"]+lista_pkmn[i]["ataque_especial"]+lista_pkmn[i]["defensa_especial"]+lista_pkmn[i]["velocidad"]
        if total_i >= 600:
            pseudo.append(lista_pkmn[i]["nombre"])
    
    if len(pseudo)<Cantidad:
        return None
    
    return pseudo