# -*- coding: utf-8 -*-
"""producto_mas_barato.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V-CIyxNjl97zc9ZpLYym4KfziffALfi9

# Reto 9: El novio tacaño
Nicolás es un novio muy amoroso, pero tiene fama de ser tacaño. Para el cumpleaños de su novia ha pedido un catálogo de artículos para escoger el regalo más barato disponible. El catálogo es un diccionario que tiene varias llaves que corresponden al nombre de los productos. El valor asociado a cada llave es el precio del producto.

Cree una función que retorne el nombre del artículo más barato en el catálogo.

Si Nicolás encuentra dos artículos igual de baratos, comprará el que tenga el nombre alfabéticamente menor (el que aparecería antes en el diccionario ignorando las mayúsculas y minúsculas).

Si el artículo más barato vale más de 10.000 pesos, Nicolás no comprará nada e invitará a su novia a ver una película en su casa.  

Su solución debe tener una función de acuerdo con la siguiente especificación:


**Nombre de la función: producto_mas_barato  **

Si lo requiere, puede agregar funciones adicionales.
"""

def producto_mas_barato(catalogo:dict)->str:
    if catalogo == {}:
        return "No hay productos para escoger"

    catalogo = sorted(catalogo.items())
    mas_barato = 1000000
   
    
    for clave, valor in catalogo:
        if mas_barato >= valor:
            mas_barato = valor
    print(mas_barato)
    
    if mas_barato > 10000:
        return None
    
    for i in range (0,len(catalogo)):
        if catalogo[i][1] == mas_barato:
            mas_barato = catalogo[i][0]
            break
        
        
    respuesta = mas_barato
    
   
    return respuesta