# -*- coding: utf-8 -*-
"""producto_mas_costoso.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Crora1ouKPTSsoz5tRvTQpIwy_5s9j9W

# Reto 10: Producto más caro de un carro de compras
Catalina necesita llevar un mejor control de sus gastos cuando hace mercado. Para esto, ha decidido construir una aplicación para registrar cada producto que agregue en su carrito de compras. Estos datos son guardados en un diccionario cuyas llaves corresponden a los nombres de los productos. El valor asociado a cada llave es el precio del producto correspondiente.

Cree una función que retorne el nombre del producto más costoso del carrito de compras. Si se encuentran dos productos igual de costosos (siendo los más costosos del carro), la función retorna el menor alfabéticamente. Por ejemplo, si los 'bananos' que compra Catalina costaran los mismo que las 'chocolatinas', la función retornaría 'bananos'  

Su solución debe tener una función de acuerdo con la siguiente especificación: 

**Nombre de la función: producto_mas_costoso**

Si lo requiere, puede agregar funciones adicionales.
"""

def producto_mas_costoso(carrito_compras:dict)->str:
    if carrito_compras == {}:
        return "No hay productos en el carrito"

    carrito_compras = sorted(carrito_compras.items())
    mas_caro = 0
   
    
    for clave, valor in carrito_compras:
        if mas_caro <= valor:
            mas_caro = valor
            
    for i in range (0,len(carrito_compras)):
        if carrito_compras[i][1] == mas_caro:
            mas_caro = carrito_compras[i][0]
            break
      
    respuesta = mas_caro
    
   
    return respuesta