# -*- coding: utf-8 -*-
"""Reto_7_capacidad_universidades.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dw2S8xQBmDpGwOcoK3-3otC7UD4owyc0

# Reto 7: capacidad_universidades

Construya la función calcular_habitantes_por_puesto que calcule la cantidad de habitantes que hay en un país, por cada estudiante inscrito en una universidad de ese país y clasificada en el ranking TIMES.

La función recibe dos DataFrames. El primero tiene la información sobre la población de cada país organizada en tres columnas: 'Pais', 'Poblacion' y 'Edad_mediana'. El segundo tiene la información sobre universidades organizada en tres columnas: 'country', con el nombre del país; 'university_name', con el nombre de una universidad del ranking; y 'num_students', con el número de estudiantes inscritos en esa universidad.

Su función debe retornar un DataFrame con las siguientes condiciones:

*   Una columna llamada 'Pais' con el nombre de los países.
*   Una columna llamada 'habitantes_por_puesto'. 

En esta última columna aparecerá la cantidad de habitantes de cada país, dividida por la cantidad total de estudiantes que hay en las universidades del país que aparecen en el ranking TIMES. 

Por ejemplo, si la población de Australia es de 25 millones de personas y hay 31 universidades que en total atienden a 740.000 estudiantes, entonces la cantidad de 'habitantes_por_puesto' será 33.8 (el número debe redondearse a 1 cifra decimal). Además, el DataFrame resultante debe estar ordenado de menor a mayor de acuerdo con la cantidad de 'habitantes_por_puesto'.

**Nota: para ordenar los resultados no tenga en cuenta las aproximaciones.**

Su solución debe tener una función de acuerdo con la siguiente especificación: 

***Nombre de la función: calcular_habitantes_por_puesto***

Si lo requiere, puede agregar funciones adicionales.
"""

import pandas as pd
import numpy as np
def calcular_habitantes_por_puesto(poblacion:pd.DataFrame,universidades:pd.DataFrame)->pd.DataFrame:
  universidades = universidades.rename(columns = {'country':'Pais'})
  universidades=universidades.groupby(['Pais'])['num_students'].sum()
  universidades= pd.DataFrame(universidades).reset_index()
  resultado = pd.merge(poblacion, universidades)
  resultado["habitantes_por_puesto"]=(resultado["Poblacion"]/resultado["num_students"])
  resultado = resultado.sort_values("habitantes_por_puesto")
  resultado["habitantes_por_puesto"]=round(resultado["habitantes_por_puesto"],1)
  resultado= resultado.drop(["num_students","Edad_mediana","Poblacion"],axis=1).reset_index(drop=True)
  return(resultado)

data = np.array([['Pais', 'Poblacion', 'Edad_mediana'],
                 ['Colombia',50000000, 37 ],
                 ['España', 20000000, 50],
                 ['Chile',45000000, 30],
                 ['Francia',25000000, 40 ],
                 ['Inglaterra',3000000,20 ],
                 ['Mexico',120000000, 25 ],
                 ['Filipinas',80000000, 40 ]])
##Este dataframe es de prueba, los datos no son reales
poblacion = pd.DataFrame(data=data[1:,1:],
             index = data[1:,0],
             columns=data[0,1:])
poblacion = poblacion.reset_index()
poblacion=poblacion.rename(columns = {'index':'Pais'})
poblacion["Poblacion"]=poblacion["Poblacion"].astype(float)
poblacion

data = np.array([['country','num_students', 'university_name'],
                 ['Francia',500000, "nacho" ],
                 ['Colombia',12000, "Nacional"],
                 ['Colombia',12000, "Distri"],
                 ['Filipinas', 20000, "andes"],
                 ['Mexico',450000, "granada"],
                 ['Chile',25000, "salle" ],
                 ['Inglaterra',3000, "peda" ],
                 ['Colombia',12000, "bolivar" ],
                 ['España',80000, "sena" ],
                 ['España',40000, "sena2"],
                 ['España',40000, "42"],
                 ["peru", 80000, "sena" ]])
##Este dataframe es de prueba, los datos no son reales
universidades = pd.DataFrame(data=data[1:,1:],
             index = data[1:,0],
             columns=data[0,1:])
universidades =universidades.reset_index()
universidades =universidades.rename(columns = {'index':'Pais'})
universidades["num_students"]=universidades["num_students"].astype(float)
universidades

calcular_habitantes_por_puesto(poblacion,universidades)